extra_ui_fields = [
    {
        "name": "updated_at",
        "type": "datetime",
        "label": "Updated At",
        "hint": "Timestamp of the last update",
        "optional": False,
        "editable": False,
        "searchable": False,
        "sortable": True,
    },
    {
        "name": "id",
        "type": "str",
        "label": "ID",
        "hint": "Unique identifier",
        "optional": False,
        "editable": False,
        "searchable": False,
        "sortable": True,
    },
]

data = {
    "id": "donations",
    "name": "Donations",
    "short_description": "A simple donations extension",
    "description": "An extension to manage donations. xxxxx",
    "owner_table": {
        "name": "Campaign",
        "fields": [
            {
                "name": "name",
                "type": "str",
                "label": "Name",
                "hint": "Name of the campaign",
                "optional": False,
                "editable": True,
                "searchable": True,
                "sortable": True,
            },
            {
                "name": "description",
                "type": "str",
                "label": "Description",
                "hint": "Description of the campaign",
                "optional": False,
                "editable": True,
                "searchable": True,
                "sortable": True,
            },
            {
                "name": "email",
                "label": "Email",
                "hint": "Contact email",
                "type": "str",
                "optional": True,
                "editable": True,
                "searchable": True,
                "sortable": True,
            },
            {
                "name": "wallet_id",
                "label": "Wallet ID",
                "hint": "Select wallet",
                "type": "wallet",
                "optional": False,
                "editable": True,
                "searchable": False,
                "sortable": False,
            },
            {
                "name": "currency",
                "label": "Currency",
                "hint": "Select currency",
                "type": "currency",
                "optional": False,
                "editable": True,
                "searchable": False,
                "sortable": False,
            },
            {
                "name": "extra",
                "type": "json",
                "optional": False,
                "editable": False,
                "searchable": False,
                "sortable": False,
            },
        ],
    },
    "client_table": {
        "name": "User Donations",
        "fields": [
            {
                "name": "amount_sats",
                "type": "int",
                "label": "Amount (sats)",
                "hint": "Amount in satoshis",
                "optional": False,
                "editable": True,
                "searchable": False,
                "sortable": True,
            },
            {
                "name": "comment",
                "label": "Comment",
                "hint": "Additional comments",
                "type": "str",
                "optional": True,
                "editable": True,
                "searchable": True,
                "sortable": True,
            },
            {
                "name": "email",
                "label": "Email",
                "hint": "Contact email",
                "type": "str",
                "optional": True,
                "editable": True,
                "searchable": True,
                "sortable": True,
            },
            {
                "name": "paid",
                "label": "Paid",
                "hint": "Indicates if the donation has been paid",
                "type": "bool",
                "optional": True,
                "editable": False,
                "searchable": False,
                "sortable": True,
            },
        ],
    },
    "settings_table": {
        "name": "Settings",
        "fields": [
            {
                "name": "max_campaign_amount_sats",
                "type": "int",
                "label": "Max Campaign Amount (sats)",
                "hint": "Maximum amount for a single campaign in satoshis",
                "optional": True,  # all settings fields are optional
                "editable": True,
                "searchable": True,
            },
            {
                "name": "description",
                "type": "str",
                "label": "Default Description",
                "hint": "Some random data here",
                "optional": True,
                "editable": True,
                "searchable": False,
            },
        ],
    },
    "public_page": {
        "has_public_page": True,
        "owner_data_fields": {
            "name": "name",
            "description": "description",
        },
        "client_data_fields": {
            "public_inputs": ["amount_sats", "comment", "email"],
        },
        "action_fields": {
            "generate_action": True,
            "wallet_id": "wallet_id",
            "currency": "currency",
            "amount": "amount_sats",
        },
    },
}
